services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: devpilot-postgres

    environment:
      POSTGRES_USER: steve
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devpilot

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  postgres_data: